import type { Driver } from "../engine/types.ts";

/**
 * Browser-storage layer for user-created content: custom decisions/personas
 * built from a template, and saved scenarios. This is deliberately the ONLY
 * module that touches `localStorage` directly — everything else works with
 * plain data, so the storage mechanism can change later (a real backend, in
 * the "Phase 2" sense) without touching the editor UI or the engine.
 *
 * A `Decision`'s `cashFlows` is a function, not data, so it can't round-trip
 * through JSON. What's actually stored here is a `templateId` (which
 * cash-flow archetype this decision uses — see src/personas/templates.ts)
 * plus the editable driver data on top of it. "Customizing" means editing
 * the assumptions that feed a small, fixed, well-tested set of formulas —
 * not authoring an arbitrary new formula in the browser.
 *
 * Two failure modes are handled deliberately differently, matching the
 * project's existing "fail loud vs. fail soft" split (see
 * src/engine/financing.ts's LoanTermsError for the loud side):
 *   - Corrupted or unreadable storage (a bad JSON blob, a disabled/private
 *     browser, a future version this code doesn't understand) is an
 *     ENVIRONMENT limitation, not a modeling error — it fails soft, falling
 *     back to an empty list, and the caller can tell the person their
 *     changes may not persist. It never throws and never crashes the page.
 *   - An invalid scenario/persona/decision the person is actively trying to
 *     import is a correctness question — that's for the caller (main.ts,
 *     using the engine's own `validatePersona`) to reject loudly, not this
 *     module's job to paper over.
 */

export const SCHEMA_VERSION = 1;

export interface StoredCustomDecision {
  id: string; // namespaced: "custom-decision:<generated>"
  templateId: string; // which built-in cash-flow archetype this decision uses
  label: string;
  description: string;
  horizonYears: number;
  discountRate: Driver;
  drivers: Driver[];
}

export interface StoredCustomPersona {
  id: string; // namespaced: "custom-persona:<generated>"
  name: string;
  tagline: string;
  decisions: StoredCustomDecision[];
}

export interface ScenarioInputs {
  loanToValuePct?: number;
  annualInterestRate?: number;
  termYears?: number;
  availableCapital?: number;
}

export interface StoredScenario {
  schemaVersion: number;
  id: string; // namespaced: "scenario:<generated>"
  name: string;
  savedAt: string; // ISO timestamp
  personaId: string; // a built-in persona id, or a custom-persona id
  /** Present iff personaId refers to a custom persona — embedded in full so
   * exporting this scenario to a file and importing it elsewhere is
   * self-contained and doesn't depend on the other device's local storage. */
  customPersona?: StoredCustomPersona;
  decisionId: string;
  inputs: ScenarioInputs;
  /** Present iff the decision this scenario points at has an active driver
   * override (edited assumptions — see the "Driver overrides" section
   * below). Embedded in full, same reasoning as `customPersona`: exporting
   * this scenario to a file and importing it elsewhere must reproduce the
   * identical result without depending on the other device's local storage
   * already having the same override saved. */
  driverOverride?: StoredDriverOverride;
  /** Any guardrail warnings that were showing when this scenario was saved
   * (see src/engine/guardrails.ts) — carried along so exporting a scenario
   * to hand to someone else also hands them the "these assumptions looked
   * unusual" context, not just the raw numbers. */
  warnings: string[];
}

const CUSTOM_PERSONAS_KEY = "sse.customPersonas";
const SCENARIOS_KEY = "sse.scenarios";
const DRIVER_OVERRIDES_KEY = "sse.driverOverrides";

export const CUSTOM_PERSONA_PREFIX = "custom-persona";
export const CUSTOM_DECISION_PREFIX = "custom-decision";
export const SCENARIO_PREFIX = "scenario";

/** Generates a namespaced id so anything user-created can never collide with,
 * and silently overwrite, a built-in persona/decision/driver id. */
export function generateId(prefix: string): string {
  const time = Date.now().toString(36);
  const rand = Math.random().toString(36).slice(2, 8);
  return `${prefix}:${time}-${rand}`;
}

/** True if this id was generated by generateId with the given prefix — the
 * cheap namespacing check used before merging user content with built-ins. */
export function hasPrefix(id: string, prefix: string): boolean {
  return id.startsWith(`${prefix}:`);
}

let memoryFallback: Map<string, string> | null = null;

function getStorage(): Storage | null {
  try {
    if (typeof localStorage === "undefined") return null;
    const probeKey = "__sse_storage_probe__";
    localStorage.setItem(probeKey, "1");
    localStorage.removeItem(probeKey);
    return localStorage;
  } catch {
    return null;
  }
}

/** Whether persistent storage is actually available in this browser (it can
 * be disabled, full, or unavailable in private-browsing mode). When false,
 * everything here still works for the current page session via an in-memory
 * fallback, but nothing survives a reload — callers should tell the person
 * that plainly rather than silently losing their work. */
export function isStorageAvailable(): boolean {
  return getStorage() !== null;
}

function readRaw(key: string): string | null {
  const storage = getStorage();
  if (storage) {
    try {
      return storage.getItem(key);
    } catch {
      return null;
    }
  }
  return memoryFallback?.get(key) ?? null;
}

function writeRaw(key: string, value: string): boolean {
  const storage = getStorage();
  if (storage) {
    try {
      storage.setItem(key, value);
      return true;
    } catch {
      return false;
    }
  }
  if (!memoryFallback) memoryFallback = new Map();
  memoryFallback.set(key, value);
  return true; // succeeded for this page session, just won't survive a reload
}

/** Parses stored JSON defensively — any failure (corrupted content, a shape
 * from a future schema version this code doesn't understand) falls back to
 * `fallback` rather than throwing. Storage corruption is an environment
 * problem, not a modeling one, so it never crashes the page. */
function safeParseArray<T>(raw: string | null, fallback: T[]): T[] {
  if (!raw) return fallback;
  try {
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? (parsed as T[]) : fallback;
  } catch {
    return fallback;
  }
}

// ---- Custom personas ----

export function loadCustomPersonas(): StoredCustomPersona[] {
  return safeParseArray<StoredCustomPersona>(readRaw(CUSTOM_PERSONAS_KEY), []);
}

/** Returns false if this couldn't be persisted (storage unavailable/full) —
 * the change still applies for the current page session either way. */
export function saveCustomPersonas(personas: StoredCustomPersona[]): boolean {
  return writeRaw(CUSTOM_PERSONAS_KEY, JSON.stringify(personas));
}

export function upsertCustomPersona(persona: StoredCustomPersona): boolean {
  const all = loadCustomPersonas();
  const idx = all.findIndex((p) => p.id === persona.id);
  if (idx >= 0) all[idx] = persona;
  else all.push(persona);
  return saveCustomPersonas(all);
}

export function deleteCustomPersona(id: string): boolean {
  const all = loadCustomPersonas().filter((p) => p.id !== id);
  return saveCustomPersonas(all);
}

// ---- Scenarios ----

export function loadScenarios(): StoredScenario[] {
  return safeParseArray<StoredScenario>(readRaw(SCENARIOS_KEY), []);
}

export function saveScenarioRecord(scenario: StoredScenario): boolean {
  const all = loadScenarios();
  const idx = all.findIndex((s) => s.id === scenario.id);
  if (idx >= 0) all[idx] = scenario;
  else all.push(scenario);
  return writeRaw(SCENARIOS_KEY, JSON.stringify(all));
}

export function deleteScenario(id: string): boolean {
  const all = loadScenarios().filter((s) => s.id !== id);
  return writeRaw(SCENARIOS_KEY, JSON.stringify(all));
}

// ---- Driver overrides (editing an existing, built-in decision's assumptions) ----

/**
 * An override replaces a built-in decision's driver DATA only — its
 * `cashFlows` formula is never touched or reproduced here, since the caller
 * (main.ts) keeps the original Decision object and only substitutes edited
 * driver values onto a clone of it. This is deliberately a different, much
 * simpler mechanism than the template/hydrate path in
 * src/personas/templates.ts, which exists for building a brand-new decision
 * that has no formula yet — editing an existing decision's numbers never
 * needs that machinery.
 */
export interface StoredDriverOverride {
  discountRate?: Driver;
  drivers: Driver[];
  /** Guardrail warnings present at the moment this was saved (see
   * src/engine/guardrails.ts) — kept so re-opening the editor later shows
   * the same context, not just the raw numbers. */
  warnings: string[];
  savedAt: string;
}

function loadAllDriverOverrides(): Record<string, StoredDriverOverride> {
  const raw = readRaw(DRIVER_OVERRIDES_KEY);
  if (!raw) return {};
  try {
    const parsed = JSON.parse(raw);
    return typeof parsed === "object" && parsed !== null && !Array.isArray(parsed) ? (parsed as Record<string, StoredDriverOverride>) : {};
  } catch {
    return {};
  }
}

export function loadDriverOverride(decisionId: string): StoredDriverOverride | undefined {
  return loadAllDriverOverrides()[decisionId];
}

export function saveDriverOverride(decisionId: string, override: Omit<StoredDriverOverride, "savedAt">): boolean {
  const all = loadAllDriverOverrides();
  all[decisionId] = { ...override, savedAt: new Date().toISOString() };
  return writeRaw(DRIVER_OVERRIDES_KEY, JSON.stringify(all));
}

export function clearDriverOverride(decisionId: string): boolean {
  const all = loadAllDriverOverrides();
  delete all[decisionId];
  return writeRaw(DRIVER_OVERRIDES_KEY, JSON.stringify(all));
}

// ---- Export / import ----

export function exportScenarioToJson(scenario: StoredScenario): string {
  return JSON.stringify(scenario, null, 2);
}

export type ImportResult = { ok: true; scenario: StoredScenario } | { ok: false; error: string };

/**
 * Parses and structurally validates an exported scenario file. This checks
 * shape and schema compatibility only — it does NOT re-run the engine's own
 * `validatePersona` on any embedded custom persona, because this module has
 * no engine dependency by design. The caller (main.ts) must run that after
 * a successful import, before treating the imported decision as runnable.
 */
export function importScenarioFromJson(json: string): ImportResult {
  let parsed: unknown;
  try {
    parsed = JSON.parse(json);
  } catch {
    return { ok: false, error: "That file isn't valid JSON." };
  }
  if (typeof parsed !== "object" || parsed === null) {
    return { ok: false, error: "That file doesn't contain a scenario object." };
  }
  const candidate = parsed as Partial<StoredScenario>;
  if (typeof candidate.schemaVersion !== "number") {
    return { ok: false, error: "That file doesn't look like a Scenario Sensitivity Engine export (no schemaVersion)." };
  }
  if (candidate.schemaVersion > SCHEMA_VERSION) {
    return {
      ok: false,
      error: `That file was saved by a newer version of this app (schema v${candidate.schemaVersion}) than this one supports (v${SCHEMA_VERSION}) — update the app before importing it.`,
    };
  }
  if (typeof candidate.personaId !== "string" || typeof candidate.decisionId !== "string") {
    return { ok: false, error: "That file is missing its persona or decision reference." };
  }
  // Re-namespace on import so importing the same file twice — or a file that
  // happens to reuse an id already present locally — can never silently
  // overwrite an existing saved scenario.
  const scenario: StoredScenario = {
    schemaVersion: candidate.schemaVersion,
    id: generateId(SCENARIO_PREFIX),
    name: typeof candidate.name === "string" ? candidate.name : "Imported scenario",
    savedAt: typeof candidate.savedAt === "string" ? candidate.savedAt : new Date().toISOString(),
    personaId: candidate.personaId,
    customPersona: candidate.customPersona,
    decisionId: candidate.decisionId,
    inputs: typeof candidate.inputs === "object" && candidate.inputs !== null ? candidate.inputs : {},
    driverOverride:
      typeof candidate.driverOverride === "object" && candidate.driverOverride !== null && Array.isArray(candidate.driverOverride.drivers) ? candidate.driverOverride : undefined,
    warnings: Array.isArray(candidate.warnings) ? candidate.warnings : [],
  };
  return { ok: true, scenario };
}
